FROM registry.access.redhat.com/ubi9 AS builder

ARG APP_VERSION

ARG USER=app
ARG UID=1000
ARG GID=1000

USER root

RUN dnf install -y git curl-minimal bash \
  && dnf clean all \
  && rm -rf /var/cache/dnf

WORKDIR /install

RUN curl -sSLO https://downloads.plex.tv/plex-media-server-new/${APP_VERSION}/redhat/plexmediaserver-${APP_VERSION}.x86_64.rpm \
  && rpm -Uvh --nodeps --noscripts --nosignature ./plexmediaserver-${APP_VERSION}.x86_64.rpm \
  && rm -f ./plexmediaserver-${APP_VERSION}.x86_64.rpm \
  && chown -R "${UID}":"${GID}" /usr/lib/plexmediaserver

ENV PATH="${PATH}:/usr/lib/plexmediaserver"

RUN mkdir -p /rt \
  && for bin in curl bash sh env coreutils sleep kill printf echo; do \
      path="$(which "$bin")"; \
      cp -p --parents "$path" /rt; \
    done \
  && for bin in CrashUploader "Plex Commercial Skipper" "Plex DLNA Server" \
    "Plex Media Fingerprinter" "Plex Media Scanner" "Plex Media Server" \
    "Plex Relay" "Plex Script Host" "Plex SQLite" "Plex Transcoder" \
    "Plex Tuner Service" curl bash sh env coreutils sleep kill printf echo; do \
      path="$(which "$bin")"; \
      ldd "$path" 2>/dev/null | awk '/=>/ {print $(NF-1)}' | grep '^/' | xargs -r -I{} cp -p --parents {} /rt; \
    done \
  && cp -rp --parents /usr/lib/plexmediaserver /rt \
  && cp -p --parents /etc/pki/tls/cert.pem /rt \
  && cp -p --parents /etc/crypto-policies/back-ends/opensslcnf.config /rt \
  && cp -p --parents /etc/crypto-policies/config /rt \
  && loader="$(ldd "$(which bash)" | awk '/ld-linux/ {print $1}')" \
  && [ -n "$loader" ] \
  && cp -p --parents "$loader" /rt

COPY entrypoint.sh /install/dist/main/
RUN chown -R "${UID}":"${GID}" /install/dist/main \
  && chmod +x /install/dist/main/entrypoint.sh \
  && cp -rp /install/dist/main /rt/app

RUN mkdir -p /rt/etc \
  && echo "${USER}:x:${UID}:" >> /etc/group \
  && echo "${USER}:x:${UID}:${GID}::/app:/bin/bash" >> /etc/passwd

RUN mkdir -p /rt/tmp \
  && chmod 777 /rt/tmp

FROM scratch

ARG USER=app
ENV UID=1000
ENV GID=1000

COPY --from=builder /rt/ /

ENV PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin" \
  PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/config/Library/Application Support" \
  PLEX_MEDIA_SERVER_HOME="/usr/lib/plexmediaserver" \
  PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS="6" \
  PLEX_MEDIA_SERVER_MAX_STACK_SIZE="3000" \
  PLEX_MEDIA_SERVER_USER="app" \
  PLEX_MEDIA_SERVER_INFO_VENDOR="Docker" \
  PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container" \
  NVIDIA_DRIVER_CAPABILITIES="compute,video,utility,graphics"

WORKDIR /app

USER ${UID}

EXPOSE 32400/tcp 8324/tcp 32469/tcp 1900/udp 32410/udp 32412/udp 32413/udp 32414/udp

VOLUME /config

ENTRYPOINT ["/app/entrypoint.sh"]
